FROM nvidia/cuda:12.0.0-runtime-ubuntu22.04
#https://hub.docker.com/layers/nvidia/cuda/12.0.0-runtime-ubuntu22.04/images/sha256-14c3601b8bad54414ab8184a4869f5a2ff44bb145f08b3fff394c46a9e522a3b?context=explore
# Install necessary packages
RUN pip install nvidia-cublas-cu12 nvidia-cudnn-cu12






